<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>BlackDiv</AssemblyName>
    <Description>Plugin for BlackDiv.</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
	<Configurations>Debug;Release</Configurations>
	<RootNamespace>BlackDiv</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prepatch\Prepatch.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
		  <HintPath>C:\EFT\BepInEx\core\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="DrakiaXYZ-BigBrain">
		  <HintPath>C:\EFT\BepInEx\plugins\DrakiaXYZ-BigBrain.dll</HintPath>
		</Reference>
		<Reference Include="MoreBotsPlugin">
		  <HintPath>..\Reference\MoreBotsAPI\MoreBotsPlugin.dll</HintPath>
		</Reference>
		<Reference Include="SAIN">
		  <HintPath>C:\EFT\BepInEx\plugins\SAIN\SAIN.dll</HintPath>
		</Reference>
		<Reference Include="spt-custom">
		  <HintPath>C:\EFT\BepInEx\plugins\spt\spt-custom.dll</HintPath>
		</Reference>
		<Reference Include="spt-singleplayer">
		  <HintPath>C:\EFT\BepInEx\plugins\spt\spt-singleplayer.dll</HintPath>
		</Reference>
		<Reference Include="spt-common">
		  <HintPath>C:\EFT\BepInEx\plugins\spt\spt-common.dll</HintPath>
		</Reference>
		<Reference Include="spt-reflection">
		  <HintPath>C:\EFT\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
		</Reference>
		<Reference Include="AnimationSystem.Types">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\AnimationSystem.Types.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx">
		  <HintPath>C:\EFT\BepInEx\core\BepInEx.dll</HintPath>
		</Reference>
		<Reference Include="bsg.console.core">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\bsg.console.core.dll</HintPath>
		</Reference>
		<Reference Include="Comfort">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
		</Reference>
		<Reference Include="Comfort.Unity">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\Comfort.Unity.dll</HintPath>
		</Reference>
		<Reference Include="DissonanceVoip">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\DissonanceVoip.dll</HintPath>
		</Reference>
		<Reference Include="ItemComponent.Types">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\ItemComponent.Types.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="Sirenix.Serialization">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Behavior\Layers\" />
	  <Folder Include="Components\" />
	  <Folder Include="Controllers\" />
	  <Folder Include="Models\" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\output\$(TargetFileName)&quot;" />
	</Target>

</Project>