<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>BlackDivPrepatch</AssemblyName>
    <Description>BlackDiv Prepatch needed to add custom bots to the client.</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release</Configurations>
    <RootNamespace>BlackDiv</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
		<Reference Include="Assembly-CSharp">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="MoreBotsPrepatch">
		  <HintPath>..\Reference\MoreBotsPrepatch.dll</HintPath>
		</Reference>
		<Reference Include="spt-common">
		  <HintPath>C:\EFT\BepInEx\plugins\spt\spt-common.dll</HintPath>
		</Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\EFT\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>C:\EFT\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>C:\EFT\BepInEx\core\Mono.Cecil.dll</HintPath>
    </Reference>
		<Reference Include="Newtonsoft.Json">
		  <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath>
		</Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\EFT\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\output\$(TargetFileName)&quot;" />
  </Target>

</Project>